schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "PublicEnvironmentInput"
  types:
    PublicEnvironmentInput:
      type: object
      description: "Input properties for Non-GEN environment"
      properties:
        non_gen_vpc_cidr:
          type: string
          description: "This specifies CIDR range for your non-GEN VPC"
          default: 10.0.0.0/16
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|24))
        subnet_one_cidr:
          type: string
          description: "The CIDR range for subnet one"
          default: 10.0.0.0/24
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|24))
        subnet_two_cidr:
          type: string
          description: "The CIDR range for subnet two"
          default: 10.0.1.0/24
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|24))
    PrivateEnvironmentInput:
      type: object
      description: "Input properties for GEN environment"
      properties:
        gen_vpc_id:
          type: string
          description: "This specifies VPC Id for your GEN VPC"
      required:
        - gen_vpc_id